# Training model

In [10]:
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [165]:
movies_df_description = pd.read_csv(r'../datasets/new_data_sets/frame_of_colab_filt_for_description.csv')
movies_df_title = pd.read_csv(r'../datasets/new_data_sets/frame_of_colab_filt_for_title.csv')
movie_info = pd.read_csv(r'../datasets/new_data_sets/movie_info.csv')

In [166]:
movie_info

,movieId,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,"Led by Woody, Andy's toys live happily in his ...",1995-11-22,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,When siblings Judy and Peter discover an encha...,1995-12-15,/bdHG5Mo83VPobeZZdlSz0Y7HQHB.jpg,/qSxeCfWUUyht9hZgaaYmtPtTkw2.jpg
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,A family wedding reignites the ancient feud be...,1995-12-22,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,/1o4vuCHpmd4DXofMYDUwpnhKiuy.jpg
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,/4wjGMwPsdlvi025ZqR4rXnFDvBz.jpg,/jZjoEKXMTDoZAGdkjhAdJaKtXSN.jpg
4,5,Father of the Bride Part II (1995),Comedy,113041,Just when George Banks has recovered from his ...,1995-12-08,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,/lEsjVrGU21BeJjF5AF9EWsihDpw.jpg
...,...,...,...,...,...,...,...,...
9717,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,5476944,"Ciel learns of a ""Aurora Society"", that is rum...",2017-01-21,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,/clFQR5zwzDrayMVVe7axo0YLFfh.jpg
9718,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,5914996,Six thousand years before Sora and Shiro were ...,2017-07-15,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,/zmJtqKaByFqYrxipeXyoAUSTD1w.jpg
9719,193585,Flint (2017),Drama,6397426,A woman deals with the toxic water scandal in ...,2017-10-28,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,/tcM6XoTYKATJyNTIuGPk4yh0g6N.jpg
9720,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,8391976,A large scale catastrophe is occurring across ...,2018-03-03,/gCfN6xWPyxphtgtLuDxT5s0eSoq.jpg,/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg
9721,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,101726,NaN,NaN,NaN,NaN

In [245]:
vectorizer_for_description = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    max_features=100000,
    lowercase=True
)
vectorizer_for_description.fit(movies_df_description['content'])

TfidfVectorizer(max_features=100000, ngram_range=(1, 2), stop_words='english')

In [246]:
vectorizer_for_title = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    min_df=2,
    max_features=100000,
    lowercase=True
)
vectorizer_for_title.fit(movies_df_title['content'])

TfidfVectorizer(max_features=100000, min_df=2, ngram_range=(1, 2),
                stop_words='english')

In [71]:
vectorizer_for_title_search = TfidfVectorizer(
    analyzer='char_wb',
    ngram_range=(1,2),
    lowercase=True
)
vectorizer_for_title_search.fit(movies_df_title['title'])

TfidfVectorizer(analyzer='char_wb', ngram_range=(1, 2))

In [74]:
tfidf_matrix_for_title_search = vectorizer_for_title_search.transform(movies_df_title['content'])

In [141]:
tfidf_matrix_for_title = vectorizer_for_title.transform(movies_df_title['content'])

In [247]:
tfidf_matrix_for_description = vectorizer_for_description.transform(movies_df_description['content'])

In [259]:
class Content_pipeline :

    def __init__ (
        self,
        content_df : pd.DataFrame,
        org_df :pd.DataFrame,
        vectorizer_for_title_search,
        vectorizer_for_description,
        tfidf_matrix_for_title_search,
        tfidf_matrix_for_description,
        tfidf_matrix_for_title
    ):
        # data frames
        self.content_df = content_df.copy()
        self.org_df = org_df
        # vectorizers
        self.vectorizer_for_title_search = vectorizer_for_title_search
        self.vectorizer_for_description = vectorizer_for_description
        # tfidf_matrices
        self.tfidf_matrix_for_title_search = tfidf_matrix_for_title_search
        self.tfidf_matrix_for_description = tfidf_matrix_for_description
        self.tfidf_matrix_for_title = tfidf_matrix_for_title
        
    # getting index of title
    @staticmethod
    def get_index(df,title):

        match = df.index[    
        df['title'].str.casefold() == title.casefold()
        ].tolist()

        return match[0]

    # function to apply year filter this returns True and False values for every movie_index if movie at index is greater than year_limit it will be true other wise false
    @staticmethod
    def yearly_filtered_movs_idxs (df,limit_year : int | None):
        filtered_idxs = (
            df['year'].notna() 
            & (df['year'] >= limit_year)
        ).to_numpy()

        return filtered_idxs

    # getting titles that match with user entered title
    @staticmethod
    def get_matched(title : str ,t_tfidf_matrix,title_vectorizer,df : pd.DataFrame):
        title_vector = title_vectorizer.transform([title])
        t_similarity = cosine_similarity(
            title_vector,
            t_tfidf_matrix
        ).ravel()
        
        top_matched_idxs = t_similarity.argsort()[::-1][:3]
        
        top_matched_t = df.iloc[top_matched_idxs]['title']
        return top_matched_t.to_numpy()
    
    def temp_find_similar_by_title(self , inp_title , n_recoms : int = 20 , limit_year : int | None = None):

        # creating empty recommended movies frame :
        columns = ['movieId','similarity_score']
        rec_movs_df = pd.DataFrame(columns=columns)

        matched_titles = self.get_matched(
            title=inp_title,
            title_vectorizer=self.vectorizer_for_title_search,
            df=self.content_df,
            t_tfidf_matrix=self.tfidf_matrix_for_title_search
        )
        
        n_matched_titles = matched_titles.shape[0]

        if n_matched_titles != 0:
            
            recoms_per_matched_title = n_recoms
            
            for title in matched_titles :
 
                crr_idx = self.get_index(self.content_df,title)
                similarity = cosine_similarity(
                    self.tfidf_matrix_for_title[crr_idx],
                    self.tfidf_matrix_for_title
                ).ravel()

                # applying year filter
                if limit_year :
                    eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year=limit_year)
                    similarity[~eligible] = -1
                    
                # removing similarity of input title, from similarity and movies that are below year limit
                similarity[crr_idx] = -1
                top_indxs_per_title = similarity.argsort()[::-1][:recoms_per_matched_title]
                rec_movs = self.content_df.iloc[top_indxs_per_title][
                    ['movieId']    
                ]

                rec_movs['similarity_score'] = similarity[top_indxs_per_title]
                rec_movs_df = pd.concat([rec_movs_df,rec_movs],ignore_index=True)
            
        else : 
            return None
        
        rec_movs_df.drop_duplicates(subset=['movieId'],inplace=True)
        top_recommendations = rec_movs_df.sort_values(
            by='similarity_score',
            ascending=False
        ).head(n_recoms)
        
        return top_recommendations
    
    # getting similar movies on top of title
    def find_similar_by_title(self , inp_title : str , n_recoms : int = 20 , limit_year : int | None = None):

        # Here I am getting movie index and finding its cosine similarity with other movies vector 
        movie_index = self.get_index(self.content_df,inp_title)
        similarity = cosine_similarity(
            self.tfidf_matrix_for_title[movie_index],
            self.tfidf_matrix_for_title
        ).ravel()
                
        # applying year filter if it exist 
        if limit_year :
            eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year=limit_year)
            similarity[~eligible] = -1
            
        # removing the searched movie from similarity matrix 
        similarity[movie_index] = -1
        
        # here I am getting top n recommended movies index 
        top_indxs_per_title = similarity.argsort()[::-1][:n_recoms]
        
        # Now I am using the index to access the predicted movies Id's from data frame
        rec_movs = self.content_df.iloc[top_indxs_per_title][
        ['movieId']    
        ]
            
        # At last I added a new column in rec_movs data frame that contains the similarity score 
        rec_movs['similarity_score'] = similarity[top_indxs_per_title]
        return rec_movs
        
    # matching movies based on top of description
    def find_similar_by_description(self,inpt_desc : str ,n_recoms : int  = 20, limit_year : int|None = None  ):
        # converting movie description into vector
        inp_desc_vect = self.vectorizer_for_description.transform([inpt_desc.lower()])
        desc_similarity = cosine_similarity(
            inp_desc_vect,
            self.tfidf_matrix_for_description
        ).ravel()
         
         # now applying year_filter 
        if limit_year :
            eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year)
            desc_similarity[~eligible] = -1
            
        # getting top movies indexes
        top_indexes = desc_similarity.argsort()[::-1][:n_recoms]
        
        # getting top movies
        top_recoms = self.content_df.iloc[top_indexes][['movieId']]
        top_recoms['similarity_score'] = desc_similarity[top_indexes]
        return top_recoms
             
    def get_movies_info(self,predicted):
        movies_info = pd.merge(predicted,self.org_df,on='movieId',how='left')
        return movies_info

In [252]:
my_pipeline = Content_pipeline(
    movies_df_title,
    movie_info,
    vectorizer_for_title_search = vectorizer_for_title_search,
    vectorizer_for_description = vectorizer_for_description,
    tfidf_matrix_for_title_search = tfidf_matrix_for_title_search,
    tfidf_matrix_for_description = tfidf_matrix_for_description,
    tfidf_matrix_for_title = tfidf_matrix_for_title
)

In [253]:
matched_titles = my_pipeline.get_matched('harry potter',title_vectorizer=vectorizer_for_title_search,t_tfidf_matrix=tfidf_matrix_for_title_search,df=movies_df_title)

In [254]:
matched_titles[0]

"Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone)"

In [255]:
by_title = my_pipeline.find_similar_by_title(inp_title=matched_titles[0],n_recoms=15,limit_year=2000)

In [260]:
t_movs = my_pipeline.get_movies_info(by_title)
t_movs

,movieId,similarity_score,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,8368,0.582651,Harry Potter and the Prisoner of Azkaban (2004),Adventure|Fantasy|IMAX,304141,Harry Potter's life is in danger once more as ...,2004-05-31,/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg,/vbk5CfaAHOjQPSAcYm6AoRRz2Af.jpg
1,40815,0.508362,Harry Potter and the Goblet of Fire (2005),Adventure|Fantasy|Thriller|IMAX,330373,"When his name emerges from the Goblet of Fire,...",2005-11-16,/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg,/cClWTo3ftVXvV1sF8vlLuWfnlph.jpg
2,5816,0.444508,Harry Potter and the Chamber of Secrets (2002),Adventure|Fantasy,295297,"Cars fly, trees fight back, and a mysterious h...",2002-11-13,/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg,/bvRnPaai6JL7XHF4K6414DdSHro.jpg
3,54001,0.344040,Harry Potter and the Order of the Phoenix (2007),Adventure|Drama|Fantasy|IMAX,373889,When a new professor's methods leave Hogwarts ...,2007-07-08,/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg,/9svsJni0pNROt53QBEj9JqZMuEK.jpg
4,69844,0.327507,Harry Potter and the Half-Blood Prince (2009),Adventure|Fantasy|Mystery|Romance|IMAX,417741,Dumbledore tries to prepare Harry for the fina...,2009-07-15,/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg,/ze6Mx4QE5mQVXRYmG2flncqqle4.jpg
5,88125,0.302753,Harry Potter and the Deathly Hallows: Part 2 (...,Action|Adventure|Drama|Fantasy|Mystery|IMAX,1201607,"Harry, Ron and Hermione continue their quest t...",2011-07-12,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg
6,81834,0.278961,Harry Potter and the Deathly Hallows: Part 1 (...,Action|Adventure|Fantasy|IMAX,926084,"Harry, Ron and Hermione walk away from their l...",2010-11-17,/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg,/5i2QAYnbN5vOZUUolLPYHTb9spe.jpg
7,50160,0.211505,Miss Potter (2006),Drama,482546,"Beatrix Potter, the author of the beloved chil...",2006-12-03,/fecGKwGABfZdMbiH1WQN9zMcOkS.jpg,/heXvhrTFCF8j84iFQtpXEKCFwGL.jpg
8,50798,0.187357,Epic Movie (2007),Adventure|Comedy,799949,When the Pevensie siblings each follow their o...,2007-01-25,/l0lGJiTzU2Ce6T31DIRWv7I0kaC.jpg,/tXVpprSIir1fL1O1sAHeLIOxxuD.jpg
9,116977,0.158957,Dumb and Dumber To (2014),Comedy,2096672,"20 years since their first adventure, Lloyd an...",2014-11-12,/cvEi0xV7TUkabJGuzulhvbMjrHi.jpg,/rYaADjAB6trEToo452FfVMoAdgl.jpg
10,6482,0.147446,Dumb and Dumberer: When Harry Met Lloyd (2003),Comedy,329028,This wacky prequel to the 1994 blockbuster goe...,2003-04-14,/qxD6P3UXASFCdbrVavceZzgOfI9.jpg,/e2Ppz6IQcukpqyYYJsRkWcsGXvT.jpg
11,4077,0.140388,"With a Friend Like Harry... (Harry, un ami qui...",Drama|Thriller,216800,"While fixing up their summer cottage, Michel a...",2000-08-15,/tQ6Ut3kPOpo3lRhPrW5QfkBDwGk.jpg,/mgNMFGVUezUAgOPJ57N2toQ7d6z.jpg
12,7149,0.126108,Something's Gotta Give (2003),Comedy|Drama|Romance,337741,"When perpetually single, aging music industry ...",2003-12-12,/1cpdqe0SpiHzzbOLq9GDUUlZdSl.jpg,/xTQXtSQQZY5ZbJ1GxEcSCRP4aWV.jpg
13,92046,0.097119,Contact High (2009),Comedy,780002,Gangster boss Carlos orders the dodgy Viennese...,2009-03-19,/uDV8vKdnYb6XJtzZqu4Lqt6m7Yh.jpg,/8IoMtDjdWsSzveGb1Y8ntZzoEpN.jpg
14,148775,0.095405,Wizards of Waverly Place: The Movie (2009),Adventure|Children|Comedy|Drama|Fantasy|Sci-Fi,1369845,"During a family vacation, Alex, a young witch,...",2009-08-28,/vrjLcGBLurVem5lXN8237qz4tyE.jpg,/9Qvc6fzE3PzodgJ9no11GlLYZJF.jpg

In [262]:
my_desc = my_pipeline.find_similar_by_description('swords battle at large scale',20,2000)

In [263]:
d_movs = my_pipeline.get_movies_info(my_desc)
d_movs

,movieId,similarity_score,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,54185,0.200052,Manufactured Landscapes (2006),Documentary,832903,MANUFACTURED LANDSCAPES is the striking new do...,2006-09-09,/bkU59j039xv2er6Y6V8PbFRcFUX.jpg,/3Klsy1O5Hh9CFYgGShlarrq2yff.jpg
1,71282,0.184538,"Food, Inc. (2008)",Documentary,1286537,Documentary filmmaker Robert Kenner examines h...,2008-09-07,/zdwN4o7OGAZGJw9T64lRAGTEP8b.jpg,/1xMMkeXynf8w11eXqEC3HCLhzt5.jpg
2,193587,0.156702,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,8391976,A large scale catastrophe is occurring across ...,2018-03-03,/gCfN6xWPyxphtgtLuDxT5s0eSoq.jpg,/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg
3,177285,0.104267,Sword Art Online The Movie: Ordinal Scale (2017),Action|Adventure|Animation|Fantasy|Sci-Fi,5544384,"In 2026, a new machine called the Augma is dev...",2017-02-18,/2szdEK0Mr0RG0nWGFVTseNQHbnP.jpg,/yFZG86Zvdy6JuIlMW9eHxlVkct5.jpg
4,168608,0.099707,Mudbound (2017),Drama,2396589,"In the post–World War II South, two families a...",2017-11-16,/tf21kSKepMOlnorszWaiFwksKU4.jpg,/m0CrcOOSUK6Ylf0pkGfGX0BdDq7.jpg
5,83827,0.096633,Marwencol (2010),Documentary,1391092,After a vicious attack leaves him brain-damage...,2010-03-12,/bdlOAvKrHe4jLO9LUCxjqOqST4X.jpg,/dcUVeAJapke6J2I1pJMBcqIU1WP.jpg
6,93502,0.092584,"Ledge, The (2011)",Drama|Thriller,1535970,A thriller in which a battle of philosophies b...,2011-05-06,/cTaDS6CTIfZ5MH189ub6oE1FATk.jpg,/fWOfr0L1ISpP3KF8qY2qG1qrxMi.jpg
7,149902,0.090896,Garm Wars: The Last Druid (2014),Action|Sci-Fi|Thriller,2504640,In a world where clone soldiers from three mil...,2014-10-24,/cz3tMdY7XPjzhEWH7hdKOn3doJ1.jpg,/l7SYQ3Dr8tGYPPki65CCcYChe3z.jpg
8,8632,0.077800,Secret Society (2002),Comedy,217788,Daisy is the love of Ken's life - she is also ...,2000-10-29,/sZ4HeEoyOkzmv6848exsbDfsNVJ.jpg,/1glsOYiUVQ1TKKb7jBrBW70Hy1M.jpg
9,71254,0.074771,Gamer (2009),Action|Sci-Fi|Thriller,1034032,Mind-control technology has taken society by a...,2009-09-03,/d5BTNmr87p7EvguTFW72vlL9l9H.jpg,/nRBt4c7X56HexYhgt9Exl7upvRo.jpg
10,91542,0.071321,Sherlock Holmes: A Game of Shadows (2011),Action|Adventure|Comedy|Crime|Mystery|Thriller,1515091,There is a new criminal mastermind at large (P...,2011-11-22,/y1MYZkwhZK6L0Jy4YMuPktzDOfn.jpg,/lWNASscWXn32Asr9vkB1wq6cKvD.jpg
11,109687,0.070869,Particle Fever (2013),Documentary,1385956,As the Large Hadron Collider is about to be la...,2013-06-14,/3MHs9BrHt6ZjlPvaL4CP1ULYV2Z.jpg,/dcaLGCuECUGRIj9IwM2VClg9fYM.jpg
12,65631,0.069051,Battle in Seattle (2007),Action|Drama,850253,"Thousands of activists arrive in Seattle, Wash...",2007-09-07,/jO8tKM4mCMXpLVd5GnmlfJByghF.jpg,/vLUqy3lVMvtdOMwa5ToIxlXa3cJ.jpg
13,116823,0.068624,The Hunger Games: Mockingjay - Part 1 (2014),Adventure|Sci-Fi|Thriller,1951265,"After surviving the Quarter Quell, Katniss fin...",2014-11-19,/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg,/lV1P1Q5gLDXVG1ZYCxZHStkcQC3.jpg
14,93326,0.067406,This Means War (2012),Action|Comedy|Romance,1596350,Two top CIA operatives wage an epic battle aga...,2012-02-14,/7d1hwECRc1NZlGfAeYE42ki7Fem.jpg,/crDw9fmbelWgmftnVCKobQHYywI.jpg
15,122900,0.067276,Ant-Man (2015),Action|Adventure|Sci-Fi,478970,Armed with the astonishing ability to shrink i...,2015-07-14,/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg,/1K3JmSNUN8OpjYsCjc0Hy0SYxAb.jpg
16,8946,0.066740,Surviving Christmas (2004),Comedy,252028,Wealthy executive Drew Latham has no close rel...,2004-09-21,/8jHtvFpCOOqp2U2qwI3L3h10cUv.jpg,/7aRm8GSxrPhJK671kVADYgmJy7w.jpg
17,103085,0.065845,Rapture-Palooza (2013),Comedy|Fantasy,1879032,Two teens battle their way through a religious...,2013-06-07,/9yc5UCe3i5mrHuIWsGgsKfI37rd.jpg,/wQfBP2dSauy1S0YZQmYD4L30c4e.jpg
18,30850,0.063682,"Merchant of Venice, The (2004)",Drama,379889,"Venice, 1596. Bassanio begs his friend Antonio...",2004-12-03,/bvpPg5oTD1qT7hjY3BOsoniYdHG.jpg,/2fX8oILb0dGsGH4E6biP2WWlf91.jpg
19,27705,0.063601,In Hell (2003),Action|Drama|Thriller,339135,A man must survive a prison where hardened cri...,2003-11-24,/vE2fYcP07fbIHoouATNErRQuNrw.jpg,/3M4JB5PtzOqXBEfHOGh4H90nDPY.jpg