# Training model

In [10]:
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [165]:
movies_df_description = pd.read_csv(r'../datasets/new_data_sets/frame_of_colab_filt_for_description.csv')
movies_df_title = pd.read_csv(r'../datasets/new_data_sets/frame_of_colab_filt_for_title.csv')
movie_info = pd.read_csv(r'../datasets/new_data_sets/movie_info.csv')

In [166]:
movie_info

,movieId,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,"Led by Woody, Andy's toys live happily in his ...",1995-11-22,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,When siblings Judy and Peter discover an encha...,1995-12-15,/bdHG5Mo83VPobeZZdlSz0Y7HQHB.jpg,/qSxeCfWUUyht9hZgaaYmtPtTkw2.jpg
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,A family wedding reignites the ancient feud be...,1995-12-22,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,/1o4vuCHpmd4DXofMYDUwpnhKiuy.jpg
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,/4wjGMwPsdlvi025ZqR4rXnFDvBz.jpg,/jZjoEKXMTDoZAGdkjhAdJaKtXSN.jpg
4,5,Father of the Bride Part II (1995),Comedy,113041,Just when George Banks has recovered from his ...,1995-12-08,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,/lEsjVrGU21BeJjF5AF9EWsihDpw.jpg
...,...,...,...,...,...,...,...,...
9717,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,5476944,"Ciel learns of a ""Aurora Society"", that is rum...",2017-01-21,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,/clFQR5zwzDrayMVVe7axo0YLFfh.jpg
9718,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,5914996,Six thousand years before Sora and Shiro were ...,2017-07-15,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,/zmJtqKaByFqYrxipeXyoAUSTD1w.jpg
9719,193585,Flint (2017),Drama,6397426,A woman deals with the toxic water scandal in ...,2017-10-28,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,/tcM6XoTYKATJyNTIuGPk4yh0g6N.jpg
9720,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,8391976,A large scale catastrophe is occurring across ...,2018-03-03,/gCfN6xWPyxphtgtLuDxT5s0eSoq.jpg,/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg
9721,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,101726,NaN,NaN,NaN,NaN

In [364]:
vectorizer_for_description = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    max_features=1000000,
    lowercase=True,
    min_df=2
)
vectorizer_for_description.fit(movies_df_description['content'])

TfidfVectorizer(max_features=1000000, min_df=2, ngram_range=(1, 2),
                stop_words='english')

In [ ]:
vectorizer_for_title = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    min_df=2,
    max_features=10000,
    lowercase=True
)
vectorizer_for_title.fit(movies_df_title['content'])

TfidfVectorizer(max_features=100000, min_df=2, ngram_range=(1, 2),
                stop_words='english')

In [368]:
vectorizer_for_title_search = TfidfVectorizer(
    analyzer='char_wb',
    ngram_range=(1,2),
    lowercase=True
)
vectorizer_for_title_search.fit(movies_df_title['title'])

TfidfVectorizer(analyzer='char_wb', ngram_range=(1, 2))

In [370]:
tfidf_matrix_for_title_search = vectorizer_for_title_search.transform(movies_df_title['title'])

In [371]:
tfidf_matrix_for_title = vectorizer_for_title.transform(movies_df_title['content'])

In [372]:
tfidf_matrix_for_description = vectorizer_for_description.transform(movies_df_description['content'])

In [373]:
class Content_pipeline :

    def __init__ (
        self,
        content_df : pd.DataFrame,
        org_df :pd.DataFrame,
        vectorizer_for_title_search,
        vectorizer_for_description,
        tfidf_matrix_for_title_search,
        tfidf_matrix_for_description,
        tfidf_matrix_for_title
    ):
        # data frames
        self.content_df = content_df.copy()
        self.org_df = org_df
        # vectorizers
        self.vectorizer_for_title_search = vectorizer_for_title_search
        self.vectorizer_for_description = vectorizer_for_description
        # tfidf_matrices
        self.tfidf_matrix_for_title_search = tfidf_matrix_for_title_search
        self.tfidf_matrix_for_description = tfidf_matrix_for_description
        self.tfidf_matrix_for_title = tfidf_matrix_for_title
        
    # getting index of title
    @staticmethod
    def get_index(df,title):

        match = df.index[    
        df['title'].str.casefold() == title.casefold()
        ].tolist()

        return match[0]

    # function to apply year filter this returns True and False values for every movie_index if movie at index is greater than year_limit it will be true other wise false
    @staticmethod
    def yearly_filtered_movs_idxs (df,limit_year : int | None):
        filtered_idxs = (
            df['year'].notna() 
            & (df['year'] >= limit_year)
        ).to_numpy()

        return filtered_idxs

    # getting titles that match with user entered title
    @staticmethod
    def get_matched(title : str ,t_tfidf_matrix,title_vectorizer,df : pd.DataFrame):
        title_vector = title_vectorizer.transform([title])
        t_similarity = cosine_similarity(
            title_vector,
            t_tfidf_matrix
        ).ravel()
        
        top_matched_idxs = t_similarity.argsort()[::-1][:3]
        
        top_matched_t = df.iloc[top_matched_idxs]['title']
        return top_matched_t.to_numpy()
    
    def temp_find_similar_by_title(self , inp_title , n_recoms : int = 20 , limit_year : int | None = None):

        # creating empty recommended movies frame :
        columns = ['movieId','similarity_score']
        rec_movs_df = pd.DataFrame(columns=columns)

        matched_titles = self.get_matched(
            title=inp_title,
            title_vectorizer=self.vectorizer_for_title_search,
            df=self.content_df,
            t_tfidf_matrix=self.tfidf_matrix_for_title_search
        )
        
        n_matched_titles = matched_titles.shape[0]

        if n_matched_titles != 0:
            
            recoms_per_matched_title = n_recoms
            
            for title in matched_titles :
 
                crr_idx = self.get_index(self.content_df,title)
                similarity = cosine_similarity(
                    self.tfidf_matrix_for_title[crr_idx],
                    self.tfidf_matrix_for_title
                ).ravel()

                # applying year filter
                if limit_year :
                    eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year=limit_year)
                    similarity[~eligible] = -1
                    
                # removing similarity of input title, from similarity and movies that are below year limit
                similarity[crr_idx] = -1
                top_indxs_per_title = similarity.argsort()[::-1][:recoms_per_matched_title]
                rec_movs = self.content_df.iloc[top_indxs_per_title][
                    ['movieId']    
                ]

                rec_movs['similarity_score'] = similarity[top_indxs_per_title]
                rec_movs_df = pd.concat([rec_movs_df,rec_movs],ignore_index=True)
            
        else : 
            return None
        
        rec_movs_df.drop_duplicates(subset=['movieId'],inplace=True)
        top_recommendations = rec_movs_df.sort_values(
            by='similarity_score',
            ascending=False
        ).head(n_recoms)
        
        return top_recommendations
    
    # getting similar movies on top of title
    def find_similar_by_title(self , inp_title : str , n_recoms : int = 20 , limit_year : int | None = None):

        # Here I am getting movie index and finding its cosine similarity with other movies vector 
        movie_index = self.get_index(self.content_df,inp_title)
        similarity = cosine_similarity(
            self.tfidf_matrix_for_title[movie_index],
            self.tfidf_matrix_for_title
        ).ravel()
                
        # applying year filter if it exist 
        if limit_year :
            eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year=limit_year)
            similarity[~eligible] = -1
            
        # removing the searched movie from similarity matrix 
        similarity[movie_index] = -1
        
        # here I am getting top n recommended movies index 
        top_indxs_per_title = similarity.argsort()[::-1][:n_recoms]
        
        # Now I am using the index to access the predicted movies Id's from data frame
        rec_movs = self.content_df.iloc[top_indxs_per_title][
        ['movieId']    
        ]
            
        # At last I added a new column in rec_movs data frame that contains the similarity score 
        rec_movs['similarity_score'] = similarity[top_indxs_per_title]
        return rec_movs
        
    # matching movies based on top of description
    def find_similar_by_description(self,inpt_desc : str ,n_recoms : int  = 20, limit_year : int|None = None  ):
        # converting movie description into vector
        inp_desc_vect = self.vectorizer_for_description.transform([inpt_desc.lower()])
        desc_similarity = cosine_similarity(
            inp_desc_vect,
            self.tfidf_matrix_for_description
        ).ravel()
         
         # now applying year_filter 
        if limit_year :
            eligible = self.yearly_filtered_movs_idxs(self.content_df,limit_year)
            desc_similarity[~eligible] = -1
            
        # getting top movies indexes
        top_indexes = desc_similarity.argsort()[::-1][:n_recoms]
        
        # getting top movies
        top_recoms = self.content_df.iloc[top_indexes][['movieId']]
        top_recoms['similarity_score'] = desc_similarity[top_indexes]
        return top_recoms
             
    def get_movies_info(self,predicted):
        movies_info = pd.merge(predicted,self.org_df,on='movieId',how='left')
        return movies_info

In [374]:
my_pipeline = Content_pipeline(
    movies_df_title,
    movie_info,
    vectorizer_for_title_search = vectorizer_for_title_search,
    vectorizer_for_description = vectorizer_for_description,
    tfidf_matrix_for_title_search = tfidf_matrix_for_title_search,
    tfidf_matrix_for_description = tfidf_matrix_for_description,
    tfidf_matrix_for_title = tfidf_matrix_for_title
)

In [380]:
matched_titles = my_pipeline.get_matched('lord of rings',title_vectorizer=vectorizer_for_title_search,t_tfidf_matrix=tfidf_matrix_for_title_search,df=movies_df_title)

In [381]:
matched_titles[0]

'Lord of the Rings, The'

In [382]:
by_title = my_pipeline.find_similar_by_title(inp_title=matched_titles[0],n_recoms=15,limit_year=2000)

In [383]:
t_movs = my_pipeline.get_movies_info(by_title)
t_movs

,movieId,similarity_score,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,4993,0.481163,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,120737,"Young hobbit Frodo Baggins, after inheriting a...",2001-12-18,/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg,/z51Wzj94hvAIsWfknifKTqKJRwp.jpg
1,5952,0.375678,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,167261,Frodo Baggins and the other members of the Fel...,2002-12-18,/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg,/6G73mNyooWAEQTpckPSnFxFoNmc.jpg
2,7153,0.321700,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,167260,As armies mass for a final battle that will de...,2003-12-17,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg
3,118696,0.210754,The Hobbit: The Battle of the Five Armies (2014),Adventure|Fantasy,2310332,"Following Smaug's attack on Laketown, Bilbo an...",2014-12-10,/xT98tLqatZPQApyRmlPL12LtiWp.jpg,/3UbaCMmqOd7mca4Y5DOzY2ZVTyX.jpg
4,98809,0.129285,"Hobbit: An Unexpected Journey, The (2012)",Adventure|Fantasy|IMAX,903624,"Bilbo Baggins, a hobbit enjoying his quiet lif...",2012-12-12,/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg,/xyXmtuvsoM5J3yNad0nvcetpBdY.jpg
5,65577,0.110154,"Tale of Despereaux, The (2008)",Adventure|Animation|Children|Comedy|Fantasy,420238,Once upon a time... in the far away kingdom of...,2008-12-18,/6bBzgQ1uJabDHeGR9QvKrHvHYzG.jpg,/zsroSDR1aERgORUtbHBczq7F0Ke.jpg
6,106489,0.099498,"Hobbit: The Desolation of Smaug, The (2013)",Adventure|Fantasy|IMAX,1170358,"The Dwarves, Bilbo and Gandalf have successful...",2013-12-11,/xQYiXsheRCDBA39DOrmaw1aSpbk.jpg,/5ZYxL6k4ZHrEmrFvmY4HZVzerxG.jpg
7,62956,0.090589,Futurama: Bender's Game (2008),Action|Adventure|Animation|Comedy|Fantasy|Sci-Fi,1054486,When Leela is insulted by a group of space-red...,2008-11-03,/bx8OVOBn5WP9TJJuOpRzyMCdzzb.jpg,/uZzVtRO2aV9gtFx9WHNZ2nR9z55.jpg
8,104074,0.081331,Percy Jackson: Sea of Monsters (2013),Adventure|Children|Fantasy,1854564,"In their quest to confront the ultimate evil, ...",2013-08-07,/tAu90qEpLqwqiZLsMqpaMVr55oN.jpg,/fvrGb6zfQaQ8RD9pC8o9vv1b7W2.jpg
9,98243,0.081167,Rise of the Guardians (2012),Adventure|Animation|Children|Fantasy|IMAX,1446192,When an evil spirit known as Pitch lays down t...,2012-11-21,/yfzmfWGjcmyugH6FZ13WcsUGiNj.jpg,/3dLjNqylxtfgKelBJse5OWqhggf.jpg
10,27731,0.081112,"Cat Returns, The (Neko no ongaeshi) (2002)",Adventure|Animation|Children|Fantasy,347618,"Young Haru rescues a cat from being run over, ...",2002-07-19,/pqyY7IEWkCWNZ7EuRStQaJITEta.jpg,/uIF0sIkLTc7BHB0WZ6Cl0dDwd5z.jpg
11,38294,0.079767,Beowulf & Grendel (2005),Action|Adventure|Drama|Fantasy,402057,The blood-soaked tale of a Norse warrior's bat...,2005-09-14,/49s4KMmF2YBJhHYTqwdvikpTztt.jpg,/jSaZ02GsGuFIGo0B2kh3FA7hQ0Y.jpg
12,6536,0.078918,Sinbad: Legend of the Seven Seas (2003),Adventure|Animation|Children|Fantasy,165982,The sailor of legend is framed by the goddess ...,2003-07-02,/yiW2L1fDiBT7AeWXrykhTNtPrr8.jpg,/j8isWEPL3PmmVh8ap3jm75qVF4p.jpg
13,65261,0.078864,Ponyo (Gake no ue no Ponyo) (2008),Adventure|Animation|Children|Fantasy,876563,"When Sosuke, a young boy who lives on a clifft...",2008-07-19,/yp8vEZflGynlEylxEesbYasc06i.jpg,/1QmEcK0w2Ub4Hm094fHbZT8vA7o.jpg
14,8965,0.078576,"Polar Express, The (2004)",Adventure|Animation|Children|Fantasy|IMAX,338348,When a doubting young boy takes an extraordina...,2004-11-10,/eOoCzH0MqeGr2taUZO4SwG416PF.jpg,/jtOvTVlkF8TlaOq94oNXRc9u2yp.jpg

In [366]:
my_desc = my_pipeline.find_similar_by_description('lord of rings',20)

In [367]:
d_movs = my_pipeline.get_movies_info(my_desc)
d_movs

,movieId,similarity_score,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,121129,0.100658,The Hungover Games (2014),Comedy,3138104,"Each year, drunk people are selected to partic...",2014-02-01,/sOqB812jWYgcHCyT2PVEk3RBtSm.jpg,/z3Q8cbwmtsVdkPDCX10XawVG3bc.jpg
1,62956,0.094420,Futurama: Bender's Game (2008),Action|Adventure|Animation|Comedy|Fantasy|Sci-Fi,1054486,When Leela is insulted by a group of space-red...,2008-11-03,/bx8OVOBn5WP9TJJuOpRzyMCdzzb.jpg,/uZzVtRO2aV9gtFx9WHNZ2nR9z55.jpg
2,7153,0.082639,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,167260,As armies mass for a final battle that will de...,2003-12-17,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg
3,41627,0.066239,Samurai Rebellion (Jôi-uchi: Hairyô tsuma shim...,Action|Drama,61847,The mother of a feudal lord's only heir is kid...,1967-05-27,/bKySGFUTgsZyn5i7s5htMVy4Xd2.jpg,/eE6ysigsKowJfJHgoaSR4GOYJw6.jpg
4,4893,0.064810,When a Stranger Calls (1979),Horror|Thriller,80130,A student babysitter has her evening disturbed...,1979-08-24,/mdhpKVuuNZcc9noZzYXruxeIxdJ.jpg,/3dK12SaczU7Tf8btq7K2F5HQg6F.jpg
5,3971,0.059404,"Private Eyes, The (1981)",Comedy|Mystery,81376,The lord and lady of a capacious manor are kil...,1980-04-17,/sIG0xrld1OW1HavH03KACNTxz0w.jpg,/yskKkKahJJ9XYjbgrufpoOZDBdn.jpg
6,6503,0.053540,Charlie's Angels: Full Throttle (2003),Action|Adventure|Comedy|Crime|Thriller,305357,The Angels are charged with finding a pair of ...,2003-06-25,/n4cdJ0Wqxb7C0HmZbcaC4eYnkIf.jpg,/rS3QJdsCPyhhQ0mJEr8VirNmOMm.jpg
7,108192,0.050363,Hotel Chevalier (Part 1 of 'The Darjeeling Lim...,Drama,1094249,"In a Paris hotel room, Jack Whitman lies on a ...",2007-10-26,/fiWLuGIUAcJtu2hs7KlcZ0O2Ix3.jpg,/kvlXOT8snP7qplRpkOSAZahH5UB.jpg
8,7482,0.040606,Enter the Dragon (1973),Action|Crime,70034,A martial artist agrees to spy on a reclusive ...,1973-08-17,/fyrh2ULEcmLpGTVLPQqFW45hqr5.jpg,/ugfBioco0L7qNvwq0d0Pl0AL8SL.jpg
9,7766,0.039047,Throne of Blood (Kumonosu jô) (1957),Action|Drama|Thriller|War,50613,"Returning to their lord's castle, samurai warr...",1957-01-15,/zaZFMNxJST0TtPd68yF7fNt1he8.jpg,/rohRr9XqTRF8YwLMGAnTprg3GnL.jpg
10,50,0.038252,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,114814,"Held in an L.A. interrogation room, Verbal Kin...",1995-07-19,/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg,/hy0Hx9fMPk2fmw26Li60z1S2giU.jpg
11,3729,0.037375,Shaft (1971),Action|Crime|Drama|Thriller,67741,Cool Black private eye John Shaft is hired by ...,1971-06-25,/7PSuOC3HI6Alf9NIlXppaxyfqqB.jpg,/c8dlIxgLwoR7DAJGrIPTrh7vNdt.jpg
12,26947,0.037303,Pusher (1996),Crime|Thriller,117407,A drug pusher grows increasingly desperate aft...,1996-08-30,/9Myfvq4e2BySE5aosX8UzV9cUME.jpg,/1ZJlf0fxLRRrAn39guNvJi4e7Im.jpg
13,75813,0.034831,Leaves of Grass (2009),Comedy|Crime|Drama|Thriller,1151359,"An Ivy League professor returns home, where hi...",2009-09-13,/dkIfBUewNDrJYL0UlNsKRUKZJYp.jpg,/uhQS0C251mo32ZJkcjfFtJ0RN9P.jpg
14,1365,0.034755,Ridicule (1996),Drama,117477,To get royal backing on a needed drainage proj...,1996-05-09,/j78rRskAapKtILalcxAmdskGtzb.jpg,/azaAwIh1G7MrqhflrmXmSdD03mT.jpg
15,6357,0.034616,High Society (1956),Comedy|Musical|Romance,49314,"With socialite Tracy Lord about to remarry, he...",1956-07-17,/eOKLignOrNN7pgTQbwCzW6WPwbD.jpg,/oV3FcC9A8gQCphOt40IcCwujNx0.jpg
16,1280,0.034517,Raise the Red Lantern (Da hong deng long gao g...,Drama,101640,"In 1920s China, 19-year-old Songlian becomes a...",1991-12-18,/j6MGZpg55cTqlHHwahBtzI2qQg1.jpg,/9UCHfC9tYojD4mMVBm0boyzYEQq.jpg
17,5590,0.033828,"Mack, The (1973)",Crime,70350,A recently-released convict becomes the most p...,1973-04-04,/xcS9bxWGFzC3cA7qAOjcIjKajSf.jpg,/yZJqFoVb687DCgkFXvG04Y2Myw.jpg
18,8795,0.033727,Musa the Warrior (Musa) (2001),Action|Adventure|Drama|War,275083,"In feudal India, a warrior who renounces his r...",2001-09-23,/wXYKA6s6iFSYerh0nwb2zySFKvB.jpg,/osSvkIHiX0WFURwUTre3RqhFjsA.jpg
19,112006,0.032594,Tangled Ever After (2012),Action|Animation|Children,2112281,The kingdom is in a festive mood as everyone g...,2012-01-13,/5IeMW79OxftIUoR5duxyQ4LW5Iy.jpg,/6qvKbLYkfXXKM82M38UmDz3IfBk.jpg

In [273]:
import joblib as jb 
from pathlib import Path
models_dir = Path("../vectorizers_and_matrices")

In [384]:
# saving vectorizers 
jb.dump(vectorizer_for_title_search,models_dir/'vectorizer_for_title_search.joblib')
jb.dump(vectorizer_for_title,models_dir/'vectorizer_for_title.joblib')
jb.dump(vectorizer_for_description,models_dir/'vectorizer_for_description.joblib')
# saving tfidf matrices
jb.dump(tfidf_matrix_for_title_search,models_dir/'tfidf_matrix_for_title_search.joblib')
jb.dump(tfidf_matrix_for_title,models_dir/'tfidf_matrix_for_title.joblib')
jb.dump(tfidf_matrix_for_description,models_dir/'tfidf_matrix_for_description.joblib')

['..\\vectorizers_and_matrices\\tfidf_matrix_for_description.joblib']