# Training model

In [1]:
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df = pd.read_csv('../datasets/new_data_sets/frame_of_colab_filt.csv')

In [3]:
df['tags'] = df['tags'].fillna("")

In [4]:
df.drop(columns='tags',inplace=True)

In [5]:
df

,Unnamed: 0,movieId,title,genres,overview,content
0,0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995) Adventure Animation Children ...
1,1,2,Jumanji (1995),Adventure Children Fantasy,When siblings Judy and Peter discover an encha...,Jumanji (1995) Adventure Children Fantasy fant...
2,2,3,Grumpier Old Men (1995),Comedy Romance,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995) Comedy Romance moldy o...
3,3,4,Waiting to Exhale (1995),Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995) Comedy Drama Romance ...
4,4,5,Father of the Bride Part II (1995),Comedy,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995) Comedy preg...
...,...,...,...,...,...,...
9606,9607,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,"Ciel learns of a ""Aurora Society"", that is rum...",Black Butler: Book of the Atlantic (2017) Acti...
9607,9608,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,Six thousand years before Sora and Shiro were ...,No Game No Life: Zero (2017) Animation Comedy ...
9608,9609,193585,Flint (2017),Drama,A woman deals with the toxic water scandal in ...,Flint (2017) Drama A woman deals with the tox...
9609,9610,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,A large scale catastrophe is occurring across ...,Bungo Stray Dogs: Dead Apple (2018) Action Ani...
9610,9611,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,"Outrageous, misogynistic and vulgar-to-the-max...",Andrew Dice Clay: Dice Rules (1991) Comedy Ou...

In [30]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),
    min_df=2,
    max_features=100000,
    lowercase=True,
    token_pattern=r"(?u)\b[^\W\d_][\w]*\b"
)
vectorizer.fit(df['content'])

TfidfVectorizer(max_features=100000, min_df=2, ngram_range=(1, 2),
                stop_words='english',
                token_pattern='(?u)\\b[^\\W\\d_][\\w]*\\b')

In [31]:
tfidf_matrix = vectorizer.transform(df['content'])

In [32]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 339867 stored elements and shape (9611, 36189)>

In [72]:
search_title = "xo kitty"

matches = df[
    df["title"].str.contains(
        search_title,
        case=False,
        na=False,
        regex=False
    )
]

titles = matches["title"].to_numpy()

In [77]:
titles

array([], dtype=object)

In [78]:
def get_index(titles,df):
    match = df.index[
    df['title'].str.casefold() == title.casefold()
    ].tolist()
    return match

In [79]:
n_recs = 15
if titles.shape[0] != 0:
    n_titles = titles.shape[0]
else : 
    n_titles = 1
    
rec_per_title = n_recs//n_titles 
for title in titles :
    crr_index = get_index(title,df)
    print(crr_index)
    similartity_matrix = cosine_similarity(
        tfidf_matrix[crr_index],
        tfidf_matrix
    ).ravel() # cosine similarity gives 2D array .ravel() convert it into 1D array
    similartity_matrix[crr_index] = -1 
    recom_movs_idx = similartity_matrix.argsort()[::-1][:10]
    recoms_for_crr_title = df.iloc[recom_movs_idx][
        ['movieId','title']
    ]
    recoms_for_crr_title['similarity'] = similartity_matrix[recom_movs_idx]
    display(recoms_for_crr_title)
    break

In [62]:
movie_title = 'Dark Knight, The (2008)'

# below code is doing that gave me the index of rows where df['title] == movie_title 
matches = df.index[
    df['title'].str.casefold() == movie_title.casefold()
].tolist()
if not matches :
    print("movie dont exist")
else : 
    print("movie founded at index : ",matches[0])
    movie_idx = matches[0]
    similartity = cosine_similarity(
    tfidf_matrix[movie_idx],
    tfidf_matrix
).ravel()

similartity[movie_idx] = -1
top_indices = similartity.argsort()[::-1][:10]
recommendations = df.iloc[top_indices][
    ["movieId", "title", "genres"]
].copy()
recommendations['similarity'] = similartity[top_indices]

movie founded at index :  6673

In [80]:
recommendations

,movieId,title,genres,similarity
7708,91529,"Dark Knight Rises, The (2012)",Action Adventure Crime IMAX,0.324620
126,153,Batman Forever (1995),Action Adventure Comedy Crime,0.237759
8008,99813,"Batman: The Dark Knight Returns, Part 2 (2013)",Action Animation,0.222259
8160,104141,Batman: Mystery of the Batwoman (2003),Action Animation Children Crime,0.207801
5607,27311,Batman Beyond: Return of the Joker (2000),Action Animation Crime Sci-Fi Thriller,0.206716
509,592,Batman (1989),Action Crime Thriller,0.201896
7962,98124,"Batman: The Dark Knight Returns, Part 1 (2012)",Action Animation Sci-Fi,0.191937
6778,60979,Batman: Gotham Knight (2008),Action Animation Crime,0.188712
9248,161354,Batman: The Killing Joke (2016),Action Animation Crime Drama,0.174965
7674,90603,Batman: Year One (2011),Action Animation Crime,0.166435

In [ ]:
1575	2116	Lord of the Rings, The (1978)	Adventure Animation Children Fantasy